apiVersion: v1
kind: Secret
metadata:
  name: energy-secrets
type: Opaque
stringData:
  mongodb-url: "mongodb://mongodb:27017/energy_forecast"
  postgresql-url: "postgresql://admin:password@postgres:5432/energy_forecast"
  infura-url: "https://sepolia.infura.io/v3/YOUR_PROJECT_ID"
  postgres-password: "password"
  contract-address: "0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb2"
